name: make-release

on: 
  push:
    tags:
    - 'v[0-9].[0-9].[0-9]'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - run: |
        cd ${{ github.workspace }}
        mkdir bin
        cd normalize-plex-files
        zip -r ../bin/normalize-plex-files.zip *
        cd ../bin
        (echo '#!/usr/bin/env python3'; cat normalize-plex-files.zip)> normalize-plex-files
        chmod a+rx normalize-plex-files

    - uses: ncipollo/release-action@v1
      with:
        draft: true
        artifacts: "bin/normalize-plex-files,bin/normalize-plex-files.zip"
        body: |
          - use `normalize-plex-files` on Linux/UNIX-like systems:
            - after download, run `chmod a+rx normalize-plex-files`
            - to run, start `normalize-plex-files`
          - use `normalize-plex-files.zip` on Windows-like systems:
            - to run, start `python3 normalize-plex-files.zip`
