name: make-release

on: 
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - run: |
        cd ${{ github.workspace }}
        mkdir bin
        cd normalize-plex-files
        zip -r ../bin/normalize-plex-files.zip *
        cd ../bin
        (echo '#!/usr/bin/env python3'; cat normalize-plex-files.zip)> normalize-plex-files
        chmod a+rx normalize-plex-files

    - uses: ncipollo/release-action@v1
      with:
        draft: true
        artifacts: "bin/normalize-plex-files,bin/normalize-plex-files.zip"
