name: make-zip

on: 
  push:
    paths:
      - 'normalize-plex-files/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
    - uses: actions/checkout@v3

    - name: zip source into one archive
      shell: bash
      run: |
        if 
          [ "x$GITHUB_REF_TYPE" = xtag ]
        then
          version="$GITHUB_REF_NAME"
        else
          version="SHA=$GITHUB_SHA"
        fi

        cd "$GITHUB_WORKSPACE" || exit 1

        versionfile="$(cat normalize-plex-files/version.py)"
        echo "${versionfile%VERSION=*}
        VERSION=\"$version\"
        " >normalize-plex-files/version.py

        mkdir bin
        cd normalize-plex-files
        zip -r ../bin/normalize-plex-files.zip *
        cd ../bin
        (echo '#!/usr/bin/env python3'; cat normalize-plex-files.zip)> normalize-plex-files
        chmod a+rx normalize-plex-files

    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: normalize-plex-files
        path: bin/normalize-plex-files
        retention-days: 1