name: make-release

on: 
  push:
    tags:
    - 'v[0-9].[0-9].[0-9]'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - run: |
        cd ${{ github.workspace }}
        mkdir bin
        cd normalize-plex-files
        zip -r ../bin/normalize-plex-files.zip *
        cd ../bin
        (echo '#!/usr/bin/env python3'; cat normalize-plex-files.zip)> normalize-plex-files
        chmod a+rx normalize-plex-files

    - uses: ncipollo/release-action@v1
      id: release
      with:
        draft: true
        artifacts: "bin/normalize-plex-files,bin/normalize-plex-files.zip"
        body: |
          # Downloadable files
          ## Linux/UNIX-like Systems
            - download `normalize-plex-files` from the list of assets below.
            - make it executable: `chmod a+rx normalize-plex-files`
            - run the executable: `./normalize-plex-files`
          ## Windows-like systems
            - download the zip archive `normalize-plex-files.zip` from the list of assets below.
            - run the zip archive: `python3 normalize-plex-files.zip`

